services:
  postgresql:
    image: postgres:17
    environment:
      - POSTGRES_USER=birblog
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blgdb
    ports:
      - "5432:5432"
    volumes:
      - blgdb_data:/var/lib/postgresql/data
    networks:
      - blg_network

networks:
  blg_network:
    driver: bridge

volumes:
  blgdb_data:
